"""Create UserDefinedTicker table

Revision ID: a127fd3fd719
Revises: f0799e212100
Create Date: 2025-02-24 19:38:59.800006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a127fd3fd719'
down_revision: Union[str, None] = 'f0799e212100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_defined_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('drift', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('jump_intensity', sa.Float(), nullable=False),
    sa.Column('jump_mean', sa.Float(), nullable=False),
    sa.Column('jump_std_dev', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_defined_tickers_id'), 'user_defined_tickers', ['id'], unique=False)
    op.create_index(op.f('ix_user_defined_tickers_ticker_code'), 'user_defined_tickers', ['ticker_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_defined_tickers_ticker_code'), table_name='user_defined_tickers')
    op.drop_index(op.f('ix_user_defined_tickers_id'), table_name='user_defined_tickers')
    op.drop_table('user_defined_tickers')
    # ### end Alembic commands ###
